- hosts: "{{ cluster }}_servers"
  tasks:
  - name: check if existing .dockercfg valid
    sudo_user: root
    sudo: yes
    shell: find /root/.dockercfg -mmin -{{ cf_auth_refresh_interval }} -type f | wc -l
    register: valid_config_count
    
  - name: copy cf config
    sudo_user: root
    sudo: yes
    copy: src=/opt/deploy/files/manager/.cf dest=/root owner=root group=root mode=0755
    when: valid_config_count.stdout == "0"
    register: copy_cf_config
    until: copy_cf_config.failed is not defined
    retries: 5
    delay: 5
      
  - name: copy ice config
    sudo_user: root
    sudo: yes
    copy: src=/opt/deploy/files/manager/.ice dest=/root owner=root group=root mode=0755  
    when: valid_config_count.stdout == "0"
    register: copy_ice_config
    until: copy_ice_config.failed is not defined
    retries: 5
    delay: 5  
    
  - name: copy docker config
    sudo_user: root
    sudo: yes
    copy: src=/opt/deploy/files/manager/.dockercfg dest=/root owner=root group=root mode=0755  
    when: valid_config_count.stdout == "0"
    register: copy_docker_config
    until: copy_docker_config.failed is not defined
    retries: 5
    delay: 5  