---

- set_fact: es_version_changed={{ ((elasticsearch_install_from_package is defined and elasticsearch_install_from_repo.changed) or (elasticsearch_install_from_package is defined and elasticsearch_install_from_package.changed)) }}

#Check if x-pack is installed
- name: Check x-pack is installed
  shell: >
    {{es_home}}/bin/elasticsearch-plugin list
  become: true
  register: feature_list
#  ignore_errors: yes
#  failed_when: "'ERROR' in x_pack_installed.stdout"
  changed_when: "feature_list.rc==1"
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

- set_fact:
    x_pack_installed: '{{feature_list.rc==0 and "x-pack" in feature_list.stdout}}'
#set_fact: x_pack_installed={{feature_list.rc==0 and "x-pack" in feature_list.stdout}}

#Remove x-pack if installed and xpack not enabled
- name: Remove x-pack plugin
  command: >
    {{es_home}}/bin/elasticsearch-plugin remove x-pack
  become: true
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 0
  when: x_pack_installed == true and (not es_enable_xpack or es_version_changed)
  notify: restart elasticsearch
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

#Install License if not installed, or it needs to be reinstalled due to ES change (above task will have removed), and its been requested.
- name: Install x-pack plugin
  command: >
    {{es_home}}/bin/elasticsearch-plugin install x-pack
  become: true
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 0
  when: (x_pack_installed == false or es_version_changed) and es_enable_xpack
  notify: restart elasticsearch
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

#We loop on all as we may need to remove some features.
#- include: elasticsearch-xpack-install.yml
#  with_items: "{{supported_xpack_features}}"
#- include: elasticsearch-xpack-install.yml item=shield
#- include: elasticsearch-xpack-install.yml item=graph
#- include: elasticsearch-xpack-install.yml item=marvel-agent
#- include: elasticsearch-xpack-install.yml item=watcher

#Shield configuration
#- include: shield/elasticsearch-shield.yml

#Add any feature specific configuration here

- name: Set Plugin Directory Permissions
  file: state=directory path={{ es_home }}/plugins owner={{ es_user }} group={{ es_group }} recurse=yes
