---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: elasticsearch-parameters.yml
  tags:
      - always

- name: stop elasticsearch service before upgrade
  include: elasticsearch-service-stop.yml
  tags:
      - always

- include: java.yml
  when: es_java_install
  tags:
      - java

- name: Include optional user and group creation.
  include: elasticsearch-optional-user.yml
  when: (es_user_id is defined) and (es_group_id is defined)
  tags:
      - install

- name: Include specific Elasticsearch
  include: elasticsearch-{{ansible_os_family}}.yml
  tags:
      - install

- include: elasticsearch-config.yml
  tags:
      - config

- include: elasticsearch-scripts.yml
  when: es_scripts
  tags:
      - scripts

- include: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
  tags:
      - plugins

  #We always execute xpack as we may need to remove features
- include: xpack/elasticsearch-xpack.yml
  tags:
      - xpack

- include: elasticsearch-service.yml
  tags:
      - service

- include: elasticsearch-templates.yml
  when: es_templates
  tags:
      - templates
      
- include: elasticsearch_seachguard.yml
  tags:
      - seachguard

- meta: flush_handlers
