---
#redstone cred for apt installation
snapshot: "{{ apt_repo }}"
redstone_cred: "{{ redstone_magic }}"

#user=logmet@us.ibm.com
#space=dev&organization=alchemy-dev-logmet@bg.vnet.ibm.com
stack_name: "{{ STACK_NAME | default('dev') }}"
cluster_name: "{{ STACK_NAME | default('test') }}"
target_api: "{{ dashboard_proxy }}"
target_metrics: "{{ sidecar_target_metrics | default('metrics.int.opvis.bluemix.net') }}"
target_logs: "{{ logs_hostname }}"
target_space_id: "{{ sidecar_metrics_target_space_id | default('633ac390-ab60-4617-ad02-2609df4f7a13') }}"
target_token: "{{ sidecar_metrics_target_token | default('upsrhztlK0yz') }}"
STATSD_HOST: localhost
STATSD_PORT: 8125
carbonrelay_port: 2013
carbonrelay_host: "{{ metrics_host | default('10.176.109.169') }}"
internal_target_space_id: "6dbd8c1b-f35e-48d9-9d28-2892c698ce93"
BufferSize: 16000
## END

