---
es_instance_name: "http"
es_conf_dir: "/etc/elasticsearch"
sysd_script: "/usr/lib/systemd/system/elasticsearch.service"
init_script: "/etc/init.d/elasticsearch"
default_file: "/etc/default/elasticsearch"
es_home: "/usr/share/elasticsearch"
java: "{% if es_java is defined %}{{es_java}}{%elif (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15.10', '>=')) %}openjdk-8-jre-headless{% else %}openjdk-7-jre-headless{% endif %}"
#add supported features here
supported_xpack_features: ["watcher","marvel-agent","graph","shield"]
