- name: sysctl recommended settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: no     # temporarily not reload, will do it later
    ignoreerrors: yes
  with_items:
    - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { name: "net.ipv4.tcp_tw_recycle", value: "0" }
    - { name: "net.ipv4.tcp_max_tw_buckets", value: "5000" }
    - { name: "net.ipv4.ip_local_port_range", value: "1024 65023" }
    - { name: "net.core.somaxconn", value: "5000" }
    - { name: "net.core.netdev_max_backlog", value: "5000" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "5000" }
    - { name: "net.ipv4.conf.default.rp_filter", value: "1" }
    - { name: "net.ipv4.conf.all.rp_filter", value: "1" }
    - { name: "net.ipv4.tcp_syncookies", value: "1" }
    - { name: "vm.mmap_min_addr", value: "65536" }
    - { name: "net.netfilter.nf_conntrack_max", value: "655360" }
    - { name: "vm.dirty_ratio", value: "10" }
    - { name: "vm.dirty_background_ratio", value: "5" }

- name: adjust nf_conntrack setting
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - modprobe ip_conntrack hashsize=81920
    - echo 81920 > /sys/module/nf_conntrack/parameters/hashsize

- name: save sysctl.conf config
  command: sysctl -p
  ignore_errors: yes
